#!/bin/bash


# build the test network


# bitcoin treats private ip addresses (RFC 1918) differently
# one effect is that connections wont spread between nodes
docker network create \
	--driver=overlay \
	--subnet=166.166.0.0/16 \
	--ip-range=166.166.0.0/16 \
	--gateway=166.166.0.1 \
	btctest

docker config create master.conf config/master.conf
docker service create --name master --network btctest \
    --config source=master.conf,target=/bitcoin.conf \
    --publish 18444:18444 \
    --publish 18443:18443 \
    otaci/bitcoin-test

docker config create eloipool.conf config/eloipool.config.py
docker service create --name pool --network btctest \
    --config source=eloipool.conf,target=/eloipool/eloipool/config.py \
    --publish 3334:3334 \
    otaci/btctest-btc-pool


# wait for master service to be up
until [ "`docker service ls -f "name=master" --format "{{.Replicas}}"`" == "1/1" ]; do
  sleep 0.1;
done;

./swarm_cmd master 1 "/bin/bash /usr/local/bin/btc_genblocks"

docker config create miner.conf config/miner.conf
docker service create --name miners --network btctest \
    --replicas 1 \
    --config source=miner.conf,target=/bitcoin.conf \
    otaci/bitcoin-test

